# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Gateway
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/gateway/' # Location of package manifests
    schedule:
      interval: 'daily'
  # Auth
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/auth/' # Location of package manifests
    schedule:
      interval: 'daily'
  # Users
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/users/' # Location of package manifests
    schedule:
      interval: 'daily'
  # Core
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/core/' # Location of package manifests
    schedule:
      interval: 'daily'
